test_function ex00 ft_strcmp.c '0 0 1 1'
test_function ex01 ft_strncmp.c '0 0 0 1 1'
test_function ex02 ft_strcat.c 'hello world'
test_function ex03 ft_strncat.c 'hello worldhello wor'
test_function ex04 ft_strstr.c 'Bar BazBar Baz(null)0'
test_function ex05 ft_strlcat.c '8hello 11hello world11hello wor'
