norm
test_function ex00 'ft_create_elem.c' 'a,0x0'
test_function ex01 'ft_list_push_front.c' 'a,b'
test_function ex02 'ft_list_size.c' '5'
test_function ex03 'ft_list_last.c' 'a'
test_function ex04 'ft_list_push_back.c' 'e'
test_function ex05 'ft_list_push_strs.c' 'hello world,0x0'
test_function ex06 'ft_list_clear.c' '0x0,0x0,0x0,0x0,0x0,0x0,'
test_function ex07 'ft_list_at.c' 'f'
test_function ex08 'ft_list_reverse.c' 'f'
test_function ex09 'ft_list_foreach.c' 'abcdef'
test_function ex10 'ft_list_foreach_if.c' 'a'
test_function ex11 'ft_list_find.c' 'd'
test_function ex12 'ft_list_remove_if.c' 'de'
