test_header ex00 'a'
test_header ex01 '1,0,0,1,I have an even number of arguments.,I have an odd number of arguments.,0a'
test_header ex02 '5,5'
test_header ex03 '42,21'
test_function ex04 'ft_strs_to_tab.c' 'a,1,c'
test_function ex05 'ft_show_tab.c'
